# Generated by Django 4.2 on 2023-04-09 18:49

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Invalid phone number', regex='^\\(?:[0-9] ?){6,14}[0-9]$')], verbose_name='Mobile'),
        ),
    ]
